/**
 * 
 */
package port;

/**
 * This code was generated by A.I. with Nemotron-3-Nano-30B-A3B-Q8_0.gguf and KoboldCpp
 */
import java.util.*;
import java.util.function.Predicate;

/**
 * Utility class that contains a stable‑partition method for {@link List}.
 */
public final class StablePartition {

    private StablePartition() { /* utility class – prevent instantiation */ }

    /**
     * Rearranges {@code list} so that all elements for which {@code test} returns {@code true}
     * appear before the elements for which it returns {@code false}, while keeping the
     * relative order inside each of those two groups.
     *
     * <p>The operation is performed *in‑place*: the original list instance is mutated and
     * the same list reference is returned.</p>
     *
     * @param <T>   the element type of the list
     * @param list  the list to be reordered; must not be {@code null}
     * @param test  predicate used to decide whether an element belongs to the “true” group
     * @return the same list instance, now reordered
     */
    public static <T> List<T> stablePartition(List<T> list, Predicate<? super T> test) {
        if (list == null) {
            throw new NullPointerException("list cannot be null");
        }
        if (test == null) {
            throw new NullPointerException("predicate cannot be null");
        }

        // Containers for the two partitions – they keep insertion order.
        List<T> trueList  = new ArrayList<>();
        List<T> falseList = new ArrayList<>();

        // One linear scan, classifying each element.
        for (T e : list) {
            if (test.test(e)) {
                trueList.add(e);
            } else {
                falseList.add(e);
            }
        }

        // Overwrite the original list with the concatenation of the two stable sub‑lists.
        // Using `set` would require random access; the safest way is to clear and addAll().
        list.clear();
        list.addAll(trueList);
        list.addAll(falseList);

        return list;   // returning the list makes it easy to use in a fluent style
    }

    /* --------------------------------------------------------------- */
    /* Demo / simple test harness                                      */
    /* --------------------------------------------------------------- */
    public static void main(String[] args) {
        List<Integer> numbers = Arrays.asList(1, 4, 3, 6, 8, 2, 5, 7);

        // Move all even numbers to the front, preserving order inside each group
        StablePartition.stablePartition(numbers,
                n -> n % 2 == 0);          // predicate: “is even”

        System.out.println(numbers);   // → [4, 6, 8, 2, 1, 3, 5, 7]
    }
}